--- #YAML:1.0
name:                XML-Feed-Aggregator
version:             0.01
abstract:            Perl module for aggregating feeds
license:             ~
author:              
    - Robin Edwards <rge@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Test::More:                    0
    URI:                           0
    XML::Feed:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
