--- #YAML:1.0
name:               XML-Feed-Aggregator
version:            0.03
abstract:           Perl module for aggregating feeds
author:
    - Robin Edwards <rge@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    DateTime:             0
    DateTime::Duration:   0
    File::Temp:           0
    namespace::autoclean:  0
    Test::More:           0
    Try::Tiny:            0
    URI:                  0
    XML::Feed:            0
    XML::Feed::Deduper:   0.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
